### ISSUE TITLE
Bloomfilters Should Be Enabled by Default

### ISSUE THREAD

**Issue by schofield** [humio/humio-helm-charts#100]
I don't recall why we excluded them originally, but this should be changed to enable bloomfilters by default.
https://github.com/humio/humio-helm-charts/blob/master/charts/humio-core/values.yaml#L40

**Comment by SaaldjorMike** [comment]
Perhaps it is time to just remove those options entirely and rely on Humio's default here?

**Comment by schofield** [comment]
Yes, was about to do a PR to that effect. 

Grant
