### ISSUE TITLE
how can I change the fluentbit image version?

### ISSUE THREAD

**Issue by brightzheng100** [humio/humio-helm-charts#124]
How can I change the `fluentbit` image version?

For example:

```sh
helm install humio-agent humio/humio-helm-charts \
  --set image=fluent/fluent-bit:1.7.2 \
  ...
```

**Comment by SaaldjorMike** [comment]
Fluent bit is installed using a subchart you need to use something like this:
```
--set humio-fluentbit.image=fluent/fluent-bit:1.7.2
```

Notice how it says `humio-fluentbit.` as the prefix. All the specific options for the fluent bit subchart can be found here along with their default values: https://github.com/humio/humio-helm-charts/blob/master/charts/humio-fluentbit/values.yaml
