### ISSUE TITLE
enableLocalVolumeProvisioner doesn't exist in chart version 0.2.7

### ISSUE THREAD

**Issue by ahmedspiir** [humio/humio-helm-charts#43]
Hi @jswoods 
I tried to use the newest version of the chart which was merged yesterday with version number 0.2.7.
I was able to see the changes related to OAuth, but i couldn't see any of the changes of `enableLocalVolumeProvisioner`.
So my guess that the script didn't update everything when I ran it and i couldn't figure out why, can you check?

**Comment by SaaldjorMike** [comment]
Hi @ahmedspiir 

I've pushed 0.2.8, hopefully that works for you.
As @jswoods mentioned in the PR the release process could use some work. The script only generates the `*.tgz` file for the release if it does not already exist.

**Comment by ahmedspiir** [comment]
Perfect, Now it's there.
Thanks for the help!
